ipc_socket = true
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555753"
blue = "#729FCF"
cyan = "#34E2E2"
green = "#8AE234"
magenta = "#AD7FA8"
red = "#EF2929"
white = "#EEEEEC"
yellow = "#FCE94F"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#3465A4"
cyan = "#06989A"
green = "#4E9A06"
magenta = "#75507B"
red = "#CC0000"
white = "#D3D7CF"
yellow = "#C4A000"

[colors.primary]
background = "#002B36"
foreground = "#8AA8B3"

# [colors.light]
# background = '#FDF6E3'
# foreground = '#657B83'
# [colors.dark]
# background = '#002B36'
# foreground = '#8AA8B3'
# [colors.monokai]
# background = '#272822'
# foreground = '#eaeaea'

[cursor]
blink_interval = 600
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
#TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 15.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Sans"
style = "Book Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
decorations_theme_variant = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0
