on: push
name: Tests
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Shellcheck
      uses: docker://jess/shellcheck:latest
      with:
        args: ./test.sh
